<?php

echo "HTTP_HOST=".$_SERVER['HTTP_HOST'];
echo $_SERVER['HTTP_USER_AGENT'];
echo $_SERVER['REMOTE_ADDR'];
echo "HTTP_HOST=".$_SERVER['PHP_SELF'];
echo "HTTP_HOST=".$_SERVER['SERVER_PORT'];
echo $_SERVER['GATEWAY_INTERFACE'];

?>